# Generated by Django 4.2.2 on 2023-10-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PORTAL_TBL',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=100)),
                ('DESCRIPTION', models.CharField(max_length=1000)),
                ('INSERT_USER_ID', models.CharField(max_length=10)),
                ('INSERT_DATE', models.DateTimeField()),
                ('UPDATE_USER_ID', models.CharField(max_length=10)),
                ('UPDATE_DATE', models.DateTimeField()),
            ],
        ),
    ]
