# Generated by Django 4.2.2 on 2023-10-24 07:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_tbl',
            name='TITLE',
            field=tinymce.models.HTMLField(),
        ),
    ]
