# Generated by Django 4.2.2 on 2023-10-24 07:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_portal_tbl_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal_tbl',
            name='DESCRIPTION',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='portal_tbl',
            name='TITLE',
            field=models.CharField(max_length=100),
        ),
    ]
