# Generated by Django 4.2.2 on 2023-11-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_portal_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VARIOUS_CD_TBL',
            fields=[
                ('ID', models.BigAutoField(default=1, primary_key=True, serialize=False)),
                ('CD_CTGRY', models.CharField(max_length=3)),
                ('CD_CTGRY_NAME', models.CharField(max_length=200)),
                ('INSERT_USER_ID', models.CharField(max_length=10)),
                ('INSERT_DATE', models.DateTimeField()),
                ('UPDATE_USER_ID', models.CharField(max_length=10)),
                ('UPDATE_DATE', models.DateTimeField()),
            ],
        ),
    ]
